/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    subscriptions: Subscription;
    households: Household;
    'household-members': HouseholdMember;
    'split-assignments': SplitAssignment;
    notifications: Notification;
    'price-records': PriceRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    households: HouseholdsSelect<false> | HouseholdsSelect<true>;
    'household-members': HouseholdMembersSelect<false> | HouseholdMembersSelect<true>;
    'split-assignments': SplitAssignmentsSelect<false> | SplitAssignmentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'price-records': PriceRecordsSelect<false> | PriceRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'user';
  avatar?: (number | null) | Media;
  currency?: ('USD' | 'EUR' | 'GBP' | 'JPY' | 'CAD' | 'AUD' | 'INR' | 'KRW' | 'BRL' | 'MXN') | null;
  /**
   * IANA timezone (e.g., "America/New_York")
   */
  timezone?: string | null;
  notificationPreferences?: {
    renewalReminders?: boolean | null;
    /**
     * Days before renewal to send reminder
     */
    reminderDaysBefore?: number | null;
    priceChangeAlerts?: boolean | null;
    weeklyDigest?: boolean | null;
    pushEnabled?: boolean | null;
    emailEnabled?: boolean | null;
  };
  /**
   * FCM device tokens for push notifications
   */
  deviceTokens?:
    | {
        token: string;
        platform?: ('ios' | 'android' | 'web') | null;
        lastUsed?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Icon name (e.g., "play-circle", "music", "cloud")
   */
  icon?: string | null;
  /**
   * Hex color code (e.g., "#FF5733")
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  user?: (number | null) | User;
  /**
   * Subscription service name (e.g., Netflix, Spotify)
   */
  name: string;
  category?: (number | null) | Category;
  /**
   * Website URL for the subscription service
   */
  websiteUrl?: string | null;
  /**
   * Logo URL - Click "Auto-fetch" to get logo automatically
   */
  logo?: string | null;
  /**
   * Brief description of the subscription
   */
  description?: string | null;
  /**
   * Regular price per billing cycle
   */
  price: number;
  currency:
    | 'USD'
    | 'EUR'
    | 'GBP'
    | 'JPY'
    | 'CAD'
    | 'AUD'
    | 'INR'
    | 'KRW'
    | 'BRL'
    | 'MXN'
    | 'VND'
    | 'THB'
    | 'SGD'
    | 'CHF'
    | 'CNY';
  /**
   * Promotional/discounted price (if any)
   */
  promoPrice?: number | null;
  /**
   * When the promotional price ends
   */
  promoEndDate?: string | null;
  billingCycle: 'daily' | 'weekly' | 'monthly' | 'yearly';
  /**
   * Repeat every X cycles (e.g., every 1 month, every 3 months)
   */
  repeatEvery: number;
  /**
   * Does this subscription auto-renew?
   */
  isRecurring?: boolean | null;
  /**
   * When the subscription started
   */
  startDate: string;
  /**
   * Calculated automatically based on billing cycle
   */
  nextBillingDate?: string | null;
  /**
   * Free trial period in days (0 = no trial)
   */
  freeTrialDays?: number | null;
  /**
   * When the free trial ends
   */
  trialEndDate?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Any additional notes
   */
  notes?: string | null;
  /**
   * Reminder settings
   */
  reminder?: {
    enabled?: boolean | null;
    /**
     * Days before billing to remind
     */
    daysBefore?: number | null;
  };
  /**
   * Share subscription costs with family members
   */
  familySharing?:
    | {
        /**
         * Family member
         */
        member?: (number | null) | User;
        /**
         * Amount they pay
         */
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  status?: ('active' | 'trial' | 'paused' | 'cancelled' | 'expired') | null;
  /**
   * Notification sent for current cycle?
   */
  notifiedForCurrentCycle?: boolean | null;
  source?: ('manual' | 'screenshot' | 'email' | 'voice') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households".
 */
export interface Household {
  id: number;
  name: string;
  description?: string | null;
  avatar?: (number | null) | Media;
  owner?: (number | null) | User;
  /**
   * Default currency for household subscriptions
   */
  currency?: ('USD' | 'EUR' | 'GBP' | 'JPY' | 'CAD' | 'AUD' | 'INR' | 'KRW' | 'BRL' | 'MXN') | null;
  /**
   * Shareable code to invite new members
   */
  inviteCode?: string | null;
  /**
   * When the invite code expires
   */
  inviteCodeExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "household-members".
 */
export interface HouseholdMember {
  id: number;
  household: number | Household;
  user: number | User;
  role: 'owner' | 'admin' | 'member';
  /**
   * Display name within this household
   */
  nickname?: string | null;
  joinedAt?: string | null;
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "split-assignments".
 */
export interface SplitAssignment {
  id: number;
  subscription: number | Subscription;
  user: number | User;
  /**
   * Percentage of the subscription cost this user is responsible for
   */
  percentage: number;
  /**
   * Calculated amount in cents (percentage * subscription price / 100)
   */
  amount?: number | null;
  /**
   * Has this split been paid/settled for the current cycle?
   */
  isSettled?: boolean | null;
  /**
   * When this split was last settled
   */
  settledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type:
    | 'renewal_reminder'
    | 'price_change'
    | 'trial_ending'
    | 'payment_failed'
    | 'household_invite'
    | 'settlement_request'
    | 'weekly_digest'
    | 'system';
  title: string;
  body: string;
  /**
   * Related subscription (if applicable)
   */
  subscription?: (number | null) | Subscription;
  /**
   * Related household (if applicable)
   */
  household?: (number | null) | Household;
  status: 'pending' | 'sent' | 'failed' | 'read';
  priority?: ('low' | 'normal' | 'high') | null;
  channels?: ('push' | 'email' | 'in_app')[] | null;
  sentAt?: string | null;
  readAt?: string | null;
  /**
   * Error message if notification failed to send
   */
  error?: string | null;
  /**
   * Additional data for the notification
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Deep link or URL to navigate when notification is tapped
   */
  actionUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-records".
 */
export interface PriceRecord {
  id: number;
  subscription: number | Subscription;
  /**
   * Price in cents at the time of recording
   */
  price: number;
  /**
   * Previous price in cents (if changed)
   */
  previousPrice?: number | null;
  currency: string;
  /**
   * Billing frequency (e.g., monthly, yearly, every 2 weeks)
   */
  frequency?: string | null;
  recordedAt: string;
  source?: ('user_update' | 'auto_detection' | 'import') | null;
  /**
   * Percentage change from previous price
   */
  changePercentage?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'households';
        value: number | Household;
      } | null)
    | ({
        relationTo: 'household-members';
        value: number | HouseholdMember;
      } | null)
    | ({
        relationTo: 'split-assignments';
        value: number | SplitAssignment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'price-records';
        value: number | PriceRecord;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  currency?: T;
  timezone?: T;
  notificationPreferences?:
    | T
    | {
        renewalReminders?: T;
        reminderDaysBefore?: T;
        priceChangeAlerts?: T;
        weeklyDigest?: T;
        pushEnabled?: T;
        emailEnabled?: T;
      };
  deviceTokens?:
    | T
    | {
        token?: T;
        platform?: T;
        lastUsed?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  category?: T;
  websiteUrl?: T;
  logo?: T;
  description?: T;
  price?: T;
  currency?: T;
  promoPrice?: T;
  promoEndDate?: T;
  billingCycle?: T;
  repeatEvery?: T;
  isRecurring?: T;
  startDate?: T;
  nextBillingDate?: T;
  freeTrialDays?: T;
  trialEndDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  notes?: T;
  reminder?:
    | T
    | {
        enabled?: T;
        daysBefore?: T;
      };
  familySharing?:
    | T
    | {
        member?: T;
        amount?: T;
        id?: T;
      };
  status?: T;
  notifiedForCurrentCycle?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households_select".
 */
export interface HouseholdsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  avatar?: T;
  owner?: T;
  currency?: T;
  inviteCode?: T;
  inviteCodeExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "household-members_select".
 */
export interface HouseholdMembersSelect<T extends boolean = true> {
  household?: T;
  user?: T;
  role?: T;
  nickname?: T;
  joinedAt?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "split-assignments_select".
 */
export interface SplitAssignmentsSelect<T extends boolean = true> {
  subscription?: T;
  user?: T;
  percentage?: T;
  amount?: T;
  isSettled?: T;
  settledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  subscription?: T;
  household?: T;
  status?: T;
  priority?: T;
  channels?: T;
  sentAt?: T;
  readAt?: T;
  error?: T;
  metadata?: T;
  actionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-records_select".
 */
export interface PriceRecordsSelect<T extends boolean = true> {
  subscription?: T;
  price?: T;
  previousPrice?: T;
  currency?: T;
  frequency?: T;
  recordedAt?: T;
  source?: T;
  changePercentage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}