/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'user-settings': UserSetting;
    media: Media;
    categories: Category;
    subscriptions: Subscription;
    households: Household;
    members: Member;
    notifications: Notification;
    'popular-services': PopularService;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'user-settings': UserSettingsSelect<false> | UserSettingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    households: HouseholdsSelect<false> | HouseholdsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'popular-services': PopularServicesSelect<false> | PopularServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  roles: ('admin' | 'user')[];
  /**
   * Monthly budget limit
   */
  budget?: number | null;
  currency?: ('USD' | 'EUR' | 'GBP' | 'JPY' | 'CAD' | 'AUD' | 'INR' | 'KRW' | 'BRL' | 'MXN' | 'VND') | null;
  /**
   * IANA timezone (e.g., "America/New_York")
   */
  timezone?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings".
 */
export interface UserSetting {
  id: number;
  /**
   * The user this settings belongs to
   */
  user: number | User;
  account?: {
    /**
     * Display name (overrides firstName lastName)
     */
    displayName?: string | null;
    /**
     * Short bio or description
     */
    bio?: string | null;
    phoneNumber?: string | null;
    /**
     * Enable two-factor authentication
     */
    twoFactorEnabled?: boolean | null;
  };
  notifications?: {
    /**
     * Receive alerts before subscriptions are due
     */
    paymentReminders?: boolean | null;
    /**
     * Days before payment to send reminder
     */
    paymentReminderDays?: number | null;
    /**
     * Get notified when subscription prices change
     */
    priceChangeAlerts?: boolean | null;
    /**
     * Alert before free trials end
     */
    freeTrialEndingAlerts?: boolean | null;
    /**
     * Receive weekly spending summary
     */
    weeklySummary?: boolean | null;
    /**
     * Receive monthly spending report
     */
    monthlySummary?: boolean | null;
    /**
     * Stay updated with new features
     */
    newFeatures?: boolean | null;
    /**
     * Receive notifications via email
     */
    emailNotifications?: boolean | null;
    /**
     * Receive push notifications
     */
    pushNotifications?: boolean | null;
  };
  payments?: {
    /**
     * Default payment method ID (from payment provider)
     */
    defaultPaymentMethod?: string | null;
    /**
     * Saved payment methods
     */
    paymentMethods?:
      | {
          type: 'credit_card' | 'debit_card' | 'paypal' | 'bank_account' | 'apple_pay' | 'google_pay';
          /**
           * Display label (e.g., "Visa ending in 4242")
           */
          label: string;
          /**
           * Last 4 digits of card/account
           */
          lastFour?: string | null;
          /**
           * Expiry date (MM/YY)
           */
          expiryDate?: string | null;
          isDefault?: boolean | null;
          /**
           * Payment provider token/ID
           */
          providerToken?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Get alerted when approaching budget limit
     */
    budgetAlerts?: boolean | null;
    /**
     * Percentage of budget to trigger alert
     */
    budgetAlertThreshold?: number | null;
  };
  general?: {
    theme?: ('light' | 'dark' | 'system') | null;
    language?: ('en' | 'es' | 'fr' | 'de' | 'pt' | 'ja' | 'ko' | 'zh-CN' | 'vi') | null;
    dateFormat?: ('MM/DD/YYYY' | 'DD/MM/YYYY' | 'YYYY-MM-DD') | null;
    startOfWeek?: ('sunday' | 'monday') | null;
    /**
     * Use compact view for subscription lists
     */
    compactView?: boolean | null;
    /**
     * Show cancelled subscriptions in lists
     */
    showCancelledSubscriptions?: boolean | null;
  };
  privacy?: {
    /**
     * Allow household members to see your subscriptions
     */
    shareDataWithHousehold?: boolean | null;
    /**
     * Help improve the app by sharing anonymous usage data
     */
    analyticsEnabled?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Make this category visible to all users
   */
  isPublic?: boolean | null;
  /**
   * Hex color code (e.g., "#FF5733")
   */
  color?: string | null;
  /**
   * Icon name (e.g., "play-circle", "music", "gamepad")
   */
  icon?: string | null;
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  owner: number | User;
  name: string;
  category?: (number | null) | Category;
  websiteUrl?: string | null;
  /**
   * Logo URL
   */
  logo?: string | null;
  description?: string | null;
  amount: number;
  currency: 'USD' | 'EUR' | 'GBP' | 'JPY' | 'CAD' | 'AUD' | 'INR' | 'KRW' | 'BRL' | 'MXN' | 'VND';
  billingCycle: 'daily' | 'weekly' | 'monthly' | 'yearly';
  /**
   * Every X billing cycles (e.g., every 3 months)
   */
  frequency?: number | null;
  promoPrice?: number | null;
  promoEndDate?: string | null;
  startDate: string;
  nextBillingDate?: string | null;
  freeTrialEndDate?: string | null;
  autoRenew?: boolean | null;
  notes?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When to send reminder
   */
  reminderDate?: string | null;
  household?: (number | null) | Household;
  /**
   * Split subscription costs with members
   */
  memberShare?:
    | {
        member: number | Member;
        /**
         * Percentage of the subscription this member pays
         */
        sharePercentage: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households".
 */
export interface Household {
  id: number;
  name: string;
  owner: number | User;
  members?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  /**
   * Budget limit for this member
   */
  budgetLimit?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  subscription: number | Subscription;
  user: number | User;
  notificationDate: string;
  sent?: boolean | null;
  method: 'email' | 'sms' | 'push';
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popular-services".
 */
export interface PopularService {
  id: number;
  /**
   * Display order (lower = higher priority)
   */
  position: number;
  name: string;
  description?: string | null;
  /**
   * URL to service logo
   */
  logo?: string | null;
  /**
   * Alt text for the logo
   */
  altText?: string | null;
  /**
   * Default category to assign when selecting this service
   */
  defaultCategory?: (number | null) | Category;
  /**
   * Suggested price in cents (optional)
   */
  suggestedPrice?: number | null;
  /**
   * Suggested billing cycle (optional)
   */
  suggestedBillingCycle?: ('weekly' | 'monthly' | 'yearly') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'user-settings';
        value: number | UserSetting;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'households';
        value: number | Household;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'popular-services';
        value: number | PopularService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  budget?: T;
  currency?: T;
  timezone?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-settings_select".
 */
export interface UserSettingsSelect<T extends boolean = true> {
  user?: T;
  account?:
    | T
    | {
        displayName?: T;
        bio?: T;
        phoneNumber?: T;
        twoFactorEnabled?: T;
      };
  notifications?:
    | T
    | {
        paymentReminders?: T;
        paymentReminderDays?: T;
        priceChangeAlerts?: T;
        freeTrialEndingAlerts?: T;
        weeklySummary?: T;
        monthlySummary?: T;
        newFeatures?: T;
        emailNotifications?: T;
        pushNotifications?: T;
      };
  payments?:
    | T
    | {
        defaultPaymentMethod?: T;
        paymentMethods?:
          | T
          | {
              type?: T;
              label?: T;
              lastFour?: T;
              expiryDate?: T;
              isDefault?: T;
              providerToken?: T;
              id?: T;
            };
        budgetAlerts?: T;
        budgetAlertThreshold?: T;
      };
  general?:
    | T
    | {
        theme?: T;
        language?: T;
        dateFormat?: T;
        startOfWeek?: T;
        compactView?: T;
        showCancelledSubscriptions?: T;
      };
  privacy?:
    | T
    | {
        shareDataWithHousehold?: T;
        analyticsEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  isPublic?: T;
  color?: T;
  icon?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  category?: T;
  websiteUrl?: T;
  logo?: T;
  description?: T;
  amount?: T;
  currency?: T;
  billingCycle?: T;
  frequency?: T;
  promoPrice?: T;
  promoEndDate?: T;
  startDate?: T;
  nextBillingDate?: T;
  freeTrialEndDate?: T;
  autoRenew?: T;
  notes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  reminderDate?: T;
  household?: T;
  memberShare?:
    | T
    | {
        member?: T;
        sharePercentage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households_select".
 */
export interface HouseholdsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  budgetLimit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  subscription?: T;
  user?: T;
  notificationDate?: T;
  sent?: T;
  method?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popular-services_select".
 */
export interface PopularServicesSelect<T extends boolean = true> {
  position?: T;
  name?: T;
  description?: T;
  logo?: T;
  altText?: T;
  defaultCategory?: T;
  suggestedPrice?: T;
  suggestedBillingCycle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}